import Darwin
let p = getiopolicy_np(IOPOL_TYPE_VFS_MATERIALIZE_DATALESS_FILES, IOPOL_SCOPE_PROCESS)
print("policy process=\(p) (ON=\(IOPOL_MATERIALIZE_DATALESS_FILES_ON) OFF=\(IOPOL_MATERIALIZE_DATALESS_FILES_OFF)) EDEADLK=\(EDEADLK)")
